
## All constants are defined here


'''SPARK'''
SPARK_APP_NAME = "IDS for LoRaWAN network"
SPARK_PORT = "4050"
SPARK_EXECUTOR_MEMORY = "5g"  
SPARK_DRIVER_MEMORY = "5g"  
SPARK_EXECUTOR_MEMORY_OVERHEAD = "2g"  # 
SPARK_NETWORK_TIMEOUT = "300s"  
SPARK_EXECUTOR_HEARTBEAT_INTERVAL = "100s"
SPARK_NUM_PARTITIONS = "30"  
SPARK_FILES_MAX_PARTITION_BYTES = "268435456"


'''CRATEDB'''
CRATEDB_HOST = 'localhost'
CRATEDB_PORT = 4201
CRATEDB_URI = f'http://{CRATEDB_HOST}:{CRATEDB_PORT}'