
## All constants are defined here


'''SPARK'''
SPARK_APP_NAME = "IDS for LoRaWAN network"
SPARK_PORT = "4050"
SPARK_EXECUTOR_MEMORY = "8g"  
SPARK_DRIVER_MEMORY = "8g"  
SPARK_EXECUTOR_MEMORY_OVERHEAD = "1g"
SPARK_NETWORK_TIMEOUT = "180s"
SPARK_EXECUTOR_HEARTBEAT_INTERVAL = "60s"
SPARK_NUM_PARTITIONS = "100"
SPARK_FILES_MAX_PARTITION_BYTES = "134217728"


'''CRATEDB'''
CRATEDB_HOST = 'localhost'
CRATEDB_PORT = 4201
CRATEDB_URI = f'http://{CRATEDB_HOST}:{CRATEDB_PORT}'